HerbalStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HerbalStore.Domain.Entities;
namespace HerbalStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

HerbalStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace HerbalStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage {get; set;}
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

HerbalStore.WebUI/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HerbalStore.Domain.Entities;
namespace HerbalStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }

        public string CurrentCategory { get; set; }
    }
}

HerbalStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HerbalStore.Domain.Abstract;
using HerbalStore.Domain.Entities;
using HerbalStore.WebUI.Models;

namespace HerbalStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        private IProductRepository repository;

        public CartController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = GetCart(),
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if(product != null)
            {
                GetCart().AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if(product != null)
            {
                GetCart().RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });    
         }







        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
    }
}

HerbalStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HerbalStore.Domain.Abstract;
namespace HerbalStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        private IProductRepository repository;
        
        public NavController(IProductRepository repo)
        {
           repository = repo;
        }
  
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);

        }
    }
}

HerbalStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using HerbalStore.Domain.Entities;
using HerbalStore.Domain.Abstract;
using HerbalStore.WebUI.Models;

namespace HerbalStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p=> category == null || p.Category == category)
              .OrderBy(p => p.ProductID)
              .Skip((page - 1) * PageSize)
              .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() :
                    repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }


    }
}

HerbalStore.WebUI/Views/Cart/Index.cshtml
@model HerbalStore.WebUI.Models.CartIndexViewModel

@{ 
    ViewBag.Title = "sklep sportowy:Twój koszyk";
}

<h2> Twój koszyk</h2>
<table class=" = "table">
    <thead>
        <tr>
            <th>Ilość</th>
            <th>Produkt</th>
            <th class="text-right">Cena</th>
            <th class="text-right">Wartość</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>

        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Razem:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl"> Kontynuuj zakupy</a>
</div>

HerbalStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>
    @Html.ActionLink("Home","List","Product", null,
    new { @class = "btn btn-block btn-default btn-lg" })
    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
   {
       controller = "Product",
       action = "List",
       category = link,
       page = 1
   },
   new {@class = "btn btn-block btn-default btn-lg"
   + (link ==ViewBag.SelectedCategory ? "btn-primary" : "") 
   }

   )


    }

HerbalStore.WebUI/Views/Product/List.cshtml
@model HerbalStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Produkty";
}



@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary", p);
}
    <div class="btn-group float-right">
        @Html.PageLinks(Model.PagingInfo, x=> Url.Action("List", 
       new { page =x, category= Model.CurrentCategory}))
    </div>

HerbalStore.WebUI/Views/Shared/ProductSummary.cshtml
@model HerbalStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right col-form-label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    <span class="lead">@Model.Description</span>
    @using(Html.BeginForm("AddToCart", "Cart")){
        <div class="pull-right">
            @Html.HiddenFor(x=>x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type = "submit" class="btn btn-success" value="Dodaj do koszyka" />
            </div>
    }

</div>

HerbalStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>

</head>
<body>

    <div class="navbar navbar-nav bg-dark" role="navigation" >
            <a class="navbar-brand" href="#">Sklep zielarski</a>
    </div>
    <div class="row panel">
        <div id="categories">
           <div class="col-sm-12 bg-success">
            @Html.Action("Menu","Nav")
           </div>

        </div>


        <div class="col-sm-8" style="background-color: #e3f2fd">
                @RenderBody()
        </div>
    </div>
</body>
</html>